### ISSUE TITLE
Incorrect data size of entry been reported

### ISSUE THREAD

**Issue by RustyKnight** [cxa/SimpleUnzipper#1]
I'm trying to process zip from https://www.data.vic.gov.au/data/dataset/ptv-timetable-and-geographic-information-2015-gtfs, which contains additional zip files.  The code reports correctly for the outer zip files but for the inner zip files, it's reporting

routes.txt @ 4294967295
calendar_dates.txt @ 4294967295
trips.txt @ 4294967295
agency.txt @ 4294967295
stops.txt @ 4294967295
calendar.txt @ 4294967295
shapes.txt @ 4294967295
stop_times.txt @ 4294967295

I verified this as well as unzipping the embedded zip files manually and loading them individually, so it's not just a unzipping issue of the code.

I also tried inspecting the zip files using Java (cause I can) and either by unzipping through the Java code or via the manually unzipped file it reports

Name                 Bytes  
agency.txt           128
routes.txt           7311
trips.txt            2372251
stops.txt            19381
calendar.txt         1490
calendar_dates.txt   80
shapes.txt           32377548
stop_times.txt       41114618

which is more accurate, so I don't think it's the Zip file...

I am also using Swift 2.0, so this might be an issue there, but I've tried a couple of other libraries and they seem to do the same thing

**Comment by cxa** [comment]
Have no idea.
