### ISSUE TITLE
High use of memory when accessing many zip archives

### ISSUE THREAD

**Issue by cmo-me** [cxa/SimpleUnzipper#5]
Very useful package! I found that iterating through a folder of zip archives resulted in a lot of memory usage. See code below which shows the issue. The issue appears to be the pointer to the bytes in the Piz struct. I have a branch that solves the memory usage and will create a pull request that you can use if you want. 

        for file in folder.files {
            print(file.url)
            archive = nil
            archive = Piz.init(fileURL: file.url)
            if let files = archive?.files {
                filesList.append(contentsOf: files)
            }
        }

**Comment by cxa** [comment]
Solved by #6. Thanks @scrubbs!
